msm: kgsl: Fix unused variable warnings
../drivers/gpu/msm/adreno_dispatch.c:294:25: error: unused variable 'drawctxt' [-Werror,-Wunused-variable]
        struct adreno_context *drawctxt = ADRENO_CONTEXT(context);
                               ^
../drivers/gpu/msm/adreno_dispatch.c:555:25: error: unused variable 'drawctxt' [-Werror,-Wunused-variable]
        struct adreno_context *drawctxt = ADRENO_CONTEXT(drawobj->context);
                               ^
  LD      sound/soc/samsung/built-in.o
  CC      drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_thermal.o
  LD      fs/proc/proc.o
  LD      sound/soc/sh/built-in.o
  LD      sound/soc/sirf/built-in.o
../drivers/gpu/msm/adreno_dispatch.c:2341:28: error: unused variable 'dispatcher' [-Werror,-Wunused-variable]
        struct adreno_dispatcher *dispatcher = &adreno_dev->dispatcher;